language: node_js
node_js:
 - 8.9.4
branches:
 only:
 - development
before_script:
 - npm install -g ionic cordova
script:
 - ionic build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 0009e4eda151da54519726e9c4a55b3430ab915b
  keep-history: true
  local-dir: www
  on:
    branch: development