language: node_js
node_js:
 - 8.9.4
branches:
 only:
 - development
before_script:
 - npm install -g ionic cordova
script:
 - ionic build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 8689e51b91d7b0399d31d1be88602684ed413e49
  keep-history: true
  local-dir: www
  on:
    branch: development